use_frameworks!

platform :ios, '10.0'

target 'InWalletSDK_Example' do
  pod 'InWalletSDK', :path => '../'

  target 'InWalletSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
